apiVersion: v1
kind: Service
metadata:
  name: fastfood-products
  labels:
    app: fastfood-products
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: fastfood-products
spec:
  type: LoadBalancer
  selector:
    app: fastfood-products-api
  ports:
    - port: 5050
      targetPort: 8080
      protocol: TCP